version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z
    container_name: MINIO
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - /data